Vagrant.configure("2") do |config|
 config.vm.define "ubuntu18" do |node1|
   node1.vm.box ="ubuntu/bionic64"
   node1.vm.hostname = 'node1'
   node1.vm.provider "virtualbox" do |v|
     v.memory = "512"
     v.cpus = 1
     v.gui = false
     v.name = "ubuntu_bionic64"
     #v.linked_clone = true
   end
   node1.vm.provision "shell", inline: <<-SHELL
   sudo apt-get update
   sudo apt-get install -y python
   SHELL
   
   node1.vm.provision "ansible" do |ansible|
     #ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
     ansible.verbose = "v"
     ansible.become = true
     ansible.playbook = "roles/role_master.yaml"
   end
  end
end
