---
- hosts: all
  become: yes
  become_user: root
  #vars_files:
  #  - ./vars.yaml
  vars:
    confluence_server: https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.3.1-x64.bin
  gather_facts: no
  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present
  - name: Start NGiNX
    service:
      name: nginx
      state: started
  - name: show users
    command: id
    register: out1
  - debug:
      var: vars
