---
  - name: install package step1
    yum:
      name: "{{ packages }}"
      #use_backend: dnf
    vars:
      packages:
      - epel-release
      - https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
  - name: Set SELinux in permissive mode until the machine is rebooted
    command: setenforce 0
    ignore_errors: true
    changed_when: false
  - name: Disable SELinux at next reboot
    selinux:
      state: disabled
  - name: restart system to reboot to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0
    
  - name: wait for 10 seconds
    pause:
      seconds: 30

  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60

  - name: update all packages
    yum:
      name: '*'
      state: latest
     
  - name: install main package for OS
    yum:
      name: "{{ packages }}"
      #use_backend: dnf
    vars:
      packages:
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk
      - curl
      - wget
      - net-tools
      - yum-utils
      - vim
      - git
      - telnet
      - openssh-server
      - bind-utils
      - sudo
      - python36
  - name: install package for connect (python,java)
    yum:
      name: "{{ packages }}"
      #use_backend: dnf
    vars:
      packages:
      - mysql-connector-java
      - mysql-community-server
      - mysql-connector-python.x86_64
      - python36-PyMySQL.noarch
      - python36-mysql.x86_64
      - python36-PyMySQL.noarch
      - python2-PyMySQL.noarch
