---
- hosts: all
  become: yes
  #vars_files:
  #  - ./vars.yaml
  vars:
    confluence_server: https://www.atlassian.com/software/confluence/downloads/binary/atlassian-confluence-7.3.1-x64.bin
  gather_facts: no
  tasks:

  - name: copy var files to remote
    copy:
      src: files/confluence-response.varfile
      dest: /home/confluence-response.varfile

  - name: check if rules file exists
    stat:
      path: /home/atlassian-confluence-7.3.1-x64.bin
    register: attlasian_files

  - set_fact:
      mypath: "/home/atlassian-confluence-7.3.1-x64.bin"
  #- debug:
  #    var: attlasian_files

  - name: Download confluence_server
    get_url:
      url: "{{ confluence_server }}"
      dest: /home/
      mode: 'u+rwx,g=rw,o=r'
      force: no
    #register: output_file
    when: attlasian_files.stat.exists == false
    

  - name: create empty file
    command: "cd /home/ && ./atlassian-confluence-7.3.1-x64.bin -q -varfile response.varfile"
