Vagrant.configure("2") do |config|
 config.vm.define "centos7" do |node1|
   node1.vm.box ="centos/7"
   node1.vm.hostname = 'node3'
   node1.vm.network :private_network, ip: "192.168.10.22"
   node1.vm.network "forwarded_port", guest: 8000, host: 8000
   node1.vm.network "forwarded_port", guest: 8090, host: 8090
   node1.vm.network "forwarded_port", guest: 3306, host: 3306
 
   node1.vm.provider "virtualbox" do |v|
     v.memory = "512"
     v.cpus = 1
   end
   node1.vm.provision "ansible" do |ansible|
     #ansible.extra_vars = { ansible_ssh_user: 'vagrant' }
     ansible.verbose = "v"
     ansible.become = true
     ansible.playbook = "roles/master_install.yaml"
     #ansible.playbook = "roles/install.yaml"
   end
  end
end
