---
  - name: copy confluence-response.varfile to  /home_dir
    copy:
      src: files/confluence-response.varfile
      dest: /home/confluence-response.varfile
      force: yes
      #owner: confluence
      #group: confluence
      mode: 'u+rwx,g=rwx,o=r'


  - name: check if rules file exists
    stat:
      path: /home/atlassian-confluence-7.3.1-x64.bin
    register: attlasian_files

  - set_fact:
      mypath: "/home/atlassian-confluence-7.3.1-x64.bin"

  - name: Download confluence_server
    get_url:
      url: "{{ confluence_server }}"
      dest: /home/
      mode: 'u+rwx,g=rw,o=r'
      force: no
    #register: output_file
    when: attlasian_files.stat.exists == false
    
  - name: Run script for start atlassian-confluence server
    become: true
    become_user: root
    shell: "cd /home/ && ./atlassian-confluence-7.3.1-x64.bin -q -varfile confluence-response.varfile"
 

  - name: run scrip /etc/init.d/
    become: true
    become_user: root
    command: /etc/init.d/confluence restart
 
  - name: task 5 show databases and connect to server mysql
    command: "mysql -h localhost -uroot -p'123456' -e 'SHOW DATABASES;'"
    register: show_db
  - debug:
      #var: show_db.stdout_lines 
      msg: "mysql -h localhost -uroot -p'123456' -e 'SHOW DATABASES;' {{ show_db.stdout_lines }}"  
 # - name: Started confluence server /etc/init.d/confluence
 #   service:
 #     name: confluence
 #     state: started
 #     enabled: yes

