---

  - name: start service mysql
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: started
      enabled: yes
    with_items:
      - mysqld
  - name: copy config mycnf_server
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      force: yes
    with_items:
      - { src: 'files/server_my.cnf.j2',dest: '/etc/my.cnf'}


  - name: Find temporary password
    shell: "echo `grep 'temporary.*root@localhost' /var/log/mysqld.log | sed 's/.*root@localhost: //'`"
    register: mysql_root_password_temp
  - debug:
      var: mysql_root_password_temp
  - name: Set new password from temporary password
    shell: 'mysql -e "SET PASSWORD = PASSWORD(''{{ old_set_root_password }}'');" --connect-expired-password -uroot -p"{{ mysql_root_password_temp.stdout }}"'
    ignore_errors: true
  - name: restart service mysql
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
      enabled: yes
    with_items:
      - mysqld
 

  - name: Create new databases with "{{ db_name }}"
    mysql_db:
      login_user: "{{ master_login_mysql | default ('root') }}"
      login_host: "{{ master_host_mysql | default ('127.0.0.1') }}"
      login_port: "{{ master_port_mysql | default ('3306') }}"
      login_password: "{{ old_set_root_password }}"
      login_unix_socket: "{{ login_unix_socket | default ('/var/lib/mysql/mysql.sock') }}"
      state: present
      name:
        - "{{ db_name }}"
      state: present
  - name: Change databases user mysql_root_password
    mysql_user:
      login_user: "{{ master_login_mysql | default ('root') }}"
      login_host: "{{ master_host_mysql | default ('127.0.0.1') }}"
      login_port: "{{ master_port_mysql | default ('3306') }}"
      login_password: "{{ old_set_root_password }}"
      login_unix_socket: "{{ login_unix_socket | default ('/var/lib/mysql/mysql.sock') }}"
      name: root
      password: "{{ master_new_root_password }}"
      state: present
      priv: "*.*:ALL,GRANT"
      state: present


  - name: restart service
    systemd:
      name: "{{ item }}"
      daemon_reload: yes
      state: restarted
      enabled: yes
    with_items:
      - mysqld
